### ISSUE TITLE
Install gcloud with CircleCI

### ISSUE THREAD

**Issue by zacharynevin** [GoogleCloudPlatform/gcloud#30]
I am trying to use CircleCI to automate my push to the google container registry. I can pull the tar file down and install it, but (new to Linux CL) I am not sure how to select a prompt:
````
Welcome to the Google Cloud SDK!

To help improve the quality of this product, we collect anonymized data on how
the SDK is used. You may choose to opt out of this collection now (by choosing
'N' at the below prompt), or at any time in the future by running the following
command:
    gcloud config set --scope=user disable_usage_reporting true

Do you want to help improve the Google Cloud SDK (Y/n)?
````
Is there a flag I can set when running the install script to disable prompts?

**Comment by zacharynevin** [comment]
I also tried using docker with the CircleCI build:

````
dependencies:
  cache_directories:
    - ~/kubernetes
  pre:
    - chmod a+x ./install-kubernetes.sh ./deploy.sh
    - docker pull google/cloud-sdk
    - docker run -v /home/ubuntu/kube:/kube -t -i --name gcloud-config google/cloud-sdk gcloud auth activate-service-account $GCLOUD_CLIENT_ID --key-file /kube/gcloud_pem.p12 --project thegraduate-981
    - ./install-kubernetes.sh
    - docker build -t thegraduate/frontend-core:$CIRCLE_SHA1 ./src
````

But then I get the error that `ERROR: (gcloud.auth.activate-service-account) [Errno 2] No such file or directory: './kube/gcloud_pem.p12'`
